#!/bin/bash -eu

STACKNAME="myob-sme-web-bff-ecr"
REGION=ap-southeast-2

operation() {
  AWS_DEFAULT_REGION=$REGION AWS_REGION=$REGION aws cloudformation describe-stack-resources --stack-name $STACKNAME > /dev/null 2>&1
  exists=$?

  if [ 0 == $exists ]; then
    echo 'update'
  else
    echo 'create'
  fi
}
op=$(operation)
echo "running $op-stack for ${STACKNAME}"

aws cloudformation ${op}-stack \
  --region ${REGION} \
  --stack-name ${STACKNAME} \
  --template-body file://aws/jupiter-ecr-template.json \
