/* eslint-disable import/prefer-default-export */
export const TEST_ORDERING_ROUTE = 'TEST_ORDERING_ROUTE';

// Checkins
export const RETRIEVE_CHECKIN = 'RETRIEVE_CHECKIN';

// Locations
export const RETRIEVE_ALL_LOCATIONS = 'RETRIEVE_ALL_LOCATIONS';
export const RETRIEVE_LOCATION_MENU = 'RETRIEVE_LOCATION_MENU';

// Members
export const RETRIEVE_ALL_MEMBERS = 'RETRIEVE_ALL_MEMBERS';
export const RETRIEVE_MEMBER = 'RETRIEVE_MEMBER';
export const CREATE_MEMBER = 'CREATE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';

// Orders
export const RETRIEVE_ALL_ORDERS = 'RETRIEVE_ALL_ORDERS';
export const RETRIEVE_ORDER = 'RETRIEVE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const RETRIEVE_ORDER_TRANSACTIONS = 'RETRIEVE_ORDER_TRANSACTIONS';
export const CREATE_ORDER_TRANSACTION = 'CREATE_ORDER_TRANSACTION';

// Reservations
export const RETRIEVE_ALL_RESERVATIONS = 'RETRIEVE_ALL_RESERVATIONS';
export const RETRIEVE_RESERVATION = 'RETRIEVE_RESERVATION';
export const CREATE_RESERVATION = 'CREATE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const CREATE_RESERVATION_CHECKIN = 'CREATE_RESERVATION_CHECKIN';

// Rewards
export const RETRIEVE_ALL_REWARDS = 'RETRIEVE_ALL_REWARDS';
export const RETRIEVE_REWARD = 'RETRIEVE_REWARD';
export const CREATE_REWARD = 'CREATE_REWARD';
export const UPDATE_ALL_REWARDS = 'UPDATE_ALL_REWARDS';
export const UPDATE_REWARD = 'UPDATE_REWARD';
export const REMOVE_REWARD = 'REMOVE_REWARD';
export const ACCEPT_REWARD = 'ACCEPT_REWARD';
export const REJECT_REWARD = 'REJECT_REWARD';
export const ACCEPT_REWARD_POINTS = 'ACCEPT_REWARD_POINTS';
export const REJECT_REWARD_POINTS = 'REJECT_REWARD_POINTS';

//Tables
export const RETRIEVE_ALL_TABLES = 'RETRIEVE_ALL_TABLES';
export const RETRIEVE_TABLE = 'RETRIEVE_TABLE';
export const RETRIEVE_TABLE_BOOKINGS = 'RETRIEVE_TABLE_BOOKINGS';
export const RETRIEVE_TABLE_CHECKINS = 'RETRIEVE_TABLE_CHECKINS';
export const RETRIEVE_TABLE_ORDERS = 'RETRIEVE_TABLE_ORDERS';

// Transactions
export const RETRIEVE_TRANSACTION = 'RETRIEVE_TRANSACTION';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';