---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "reporting-web-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "reporting-web"
  template:
    metadata:
      labels:
        app: "reporting-web"
    spec:
      containers:
        - image: "nginx:alpine"
          name: nginx
          ports:
            - containerPort: 80
 

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: "reporting-web-service"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "reporting-web"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    "kubernetes.io/tls-acme": "true"
  name: "reporting-web-ingress"
spec:
  rules:
    - host: "reporting-web.svc.platform.myobdev.com"
      http:
        paths:
          - backend:
              serviceName: "reporting-web-service"
              servicePort: 80
            path: /
  tls:
    - hosts:
        - "reporting-web.svc.platform.myobdev.com"
      secretName: "reporting-web-tls"